name: vepc-synchronizer
accessor:
  username: xosadmin@opencord.org
  password: "@/opt/xos/services/vepc/credentials/xosadmin@opencord.org"
blueprints:
  - name: build
    networks:
      - name: s1u_network
        subnet: 111.0.0.0/24
        permit_all_slices: True
        template: s1u_template
      - name: s11_network
        subnet: 112.0.0.0/24
        permit_all_slices: True
        template: s11_template
      - name: nbi_network
        subnet: 113.0.0.0/24
        permit_all_slices: True
        template: nbi_template
      - name: sbi_network
        subnet: 114.0.0.0/24
        permit_all_slices: True
        template: sbi_template
      - name: sgi_network
        subnet: 115.0.0.0/24
        permit_all_slices: True
        template: sgi_template
      - name: spgw_network
        subnet: 117.0.0.0/24
        permit_all_slices: True
        template: spgw_template
    graph:
      - name: VENBServiceInstance
        networks:
          - management
          - s1u_network
          - sgi_network
          - s11_network
      - name: VSPGWCTenant
        networks:
          - management
          - s11_network
          - spgw_network
        links:
          - name: VENBServiceInstance
            networks:
              - s11_network
          - name: VSPGWUTenant
            networks:
              - spgw_network
      - name: VSPGWUTenant
        networks:
          - management
          - s1u_network
          - sgi_network
          - spgw_network
        links:
          - name: VENBServiceInstance
            networks:
              - s1u_network
              - sgi_network

  - name: oaiepc
    networks:
      - name: s1mme_network
        subnet: 111.0.0.0/24
        permit_all_slices: True
        template: oai_s1mme_template
      - name: s1u_network
        subnet: 112.0.0.0/24
        permit_all_slices: True
        template: oai_s1u_template
      - name: s6a_network
        subnet: 113.0.0.0/24
        permit_all_slices: True
        template: s6a_template
      - name: s11_network
        subnet: 114.0.0.0/24
        permit_all_slices: True
        template: s11_template
      - name: flat_sgi_network
        subnet: 115.0.0.0/24
        permit_all_slices: True
        template: flat_sgi_template
    graph:
      - name: VHSSTenant
        networks:
          - management
          - s6a_network
          - flat_sgi_network

      - name: OAISPGWServiceInstance
        networks:
          - management
          - s1u_network
          - flat_sgi_network
          - s11_network

      - name: VMMETenant
        networks:
          - management
          - s6a_network
          - s11_network
          - s1mme_network
        links:
          - name: VHSSTenant
            networks:
              - s6a_network
          - name: OAISPGWServiceInstance
            networks:
              - s11_network

dependency_graph: "/opt/xos/synchronizers/epc-service/model-deps"
#steps_dir: "/opt/xos/synchronizers/epc-service/steps"
sys_dir: "/opt/xos/synchronizers/epc-service/sys"
model_policies_dir: "/opt/xos/synchronizers/epc-service/model_policies"
